/*
 * This file is generated by jOOQ.
 */
package com.github.budgerigar.db.jooq;


import com.github.budgerigar.db.jooq.tables.BgrigarDocument;
import com.github.budgerigar.db.jooq.tables.records.BgrigarDocumentRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BgrigarDocumentRecord> CONSTRAINT_7 = Internal.createUniqueKey(BgrigarDocument.BGRIGAR_DOCUMENT, DSL.name("CONSTRAINT_7"), new TableField[] { BgrigarDocument.BGRIGAR_DOCUMENT.ID }, true);
}
