/*
 * This file is generated by jOOQ.
 */
package com.github.budgerigar.db.jooq;


import com.github.budgerigar.db.jooq.tables.BgrigarDocument;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.BGRIGAR_DOCUMENT</code>.
     */
    public static final BgrigarDocument BGRIGAR_DOCUMENT = BgrigarDocument.BGRIGAR_DOCUMENT;
}
