spring:
  elasticsearch:
    rest:
      uris: http://192.168.159.1:9200
      connection-timeout: 5000
      read-timeout: 60000
  datasource:
    driverClassName: org.h2.Driver
    username: admin
    password: admin123
    url: jdbc:h2:d:/sql/dbh2_bgrigar
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      
      

logging:
  level:
    io.grpc: DEBUG
    net.devh.boot.grpc: DEBUG