spring:
  datasource:
    driverClassName: org.h2.Driver
    username: admin
    password: admin123
    url: jdbc:h2:d:/sql/dbh2_bgrigar
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false