/*
 * This file is generated by jOOQ.
 */
package com.github.budgerigar.db.jooq.tables.records;


import com.github.budgerigar.db.jooq.tables.BgrigarDocument;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BgrigarDocumentRecord extends UpdatableRecordImpl<BgrigarDocumentRecord> implements Record7<Integer, String, String, String, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.BGRIGAR_DOCUMENT.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.BGRIGAR_DOCUMENT.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.BGRIGAR_DOCUMENT.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.BGRIGAR_DOCUMENT.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.BGRIGAR_DOCUMENT.TITLE</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.BGRIGAR_DOCUMENT.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.BGRIGAR_DOCUMENT.EXTENTION</code>.
     */
    public void setExtention(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.BGRIGAR_DOCUMENT.EXTENTION</code>.
     */
    public String getExtention() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.BGRIGAR_DOCUMENT.PATH</code>.
     */
    public void setPath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.BGRIGAR_DOCUMENT.PATH</code>.
     */
    public String getPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.BGRIGAR_DOCUMENT.LAST_MODIFIED</code>.
     */
    public void setLastModified(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.BGRIGAR_DOCUMENT.LAST_MODIFIED</code>.
     */
    public LocalDateTime getLastModified() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>PUBLIC.BGRIGAR_DOCUMENT.CONTENT</code>.
     */
    public void setContent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.BGRIGAR_DOCUMENT.CONTENT</code>.
     */
    public String getContent() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, LocalDateTime, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, LocalDateTime, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BgrigarDocument.BGRIGAR_DOCUMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return BgrigarDocument.BGRIGAR_DOCUMENT.NAME;
    }

    @Override
    public Field<String> field3() {
        return BgrigarDocument.BGRIGAR_DOCUMENT.TITLE;
    }

    @Override
    public Field<String> field4() {
        return BgrigarDocument.BGRIGAR_DOCUMENT.EXTENTION;
    }

    @Override
    public Field<String> field5() {
        return BgrigarDocument.BGRIGAR_DOCUMENT.PATH;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return BgrigarDocument.BGRIGAR_DOCUMENT.LAST_MODIFIED;
    }

    @Override
    public Field<String> field7() {
        return BgrigarDocument.BGRIGAR_DOCUMENT.CONTENT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public String component4() {
        return getExtention();
    }

    @Override
    public String component5() {
        return getPath();
    }

    @Override
    public LocalDateTime component6() {
        return getLastModified();
    }

    @Override
    public String component7() {
        return getContent();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public String value4() {
        return getExtention();
    }

    @Override
    public String value5() {
        return getPath();
    }

    @Override
    public LocalDateTime value6() {
        return getLastModified();
    }

    @Override
    public String value7() {
        return getContent();
    }

    @Override
    public BgrigarDocumentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BgrigarDocumentRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public BgrigarDocumentRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public BgrigarDocumentRecord value4(String value) {
        setExtention(value);
        return this;
    }

    @Override
    public BgrigarDocumentRecord value5(String value) {
        setPath(value);
        return this;
    }

    @Override
    public BgrigarDocumentRecord value6(LocalDateTime value) {
        setLastModified(value);
        return this;
    }

    @Override
    public BgrigarDocumentRecord value7(String value) {
        setContent(value);
        return this;
    }

    @Override
    public BgrigarDocumentRecord values(Integer value1, String value2, String value3, String value4, String value5, LocalDateTime value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BgrigarDocumentRecord
     */
    public BgrigarDocumentRecord() {
        super(BgrigarDocument.BGRIGAR_DOCUMENT);
    }

    /**
     * Create a detached, initialised BgrigarDocumentRecord
     */
    public BgrigarDocumentRecord(Integer id, String name, String title, String extention, String path, LocalDateTime lastModified, String content) {
        super(BgrigarDocument.BGRIGAR_DOCUMENT);

        setId(id);
        setName(name);
        setTitle(title);
        setExtention(extention);
        setPath(path);
        setLastModified(lastModified);
        setContent(content);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BgrigarDocumentRecord
     */
    public BgrigarDocumentRecord(com.github.budgerigar.db.jooq.tables.pojos.BgrigarDocument value) {
        super(BgrigarDocument.BGRIGAR_DOCUMENT);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setTitle(value.getTitle());
            setExtention(value.getExtention());
            setPath(value.getPath());
            setLastModified(value.getLastModified());
            setContent(value.getContent());
            resetChangedOnNotNull();
        }
    }
}
